# Generated by Django 6.0.6 on 2026-06-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0003_address_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SanghaSevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sangha_sevi_id', models.CharField(max_length=30, unique=True)),
                ('joining_date', models.DateField()),
                ('renewal_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membershipstatus')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membershiptype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='foundation.organization')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='foundation.person')),
            ],
            options={
                'db_table': 'sangha_sevi',
                'ordering': ['sangha_sevi_id'],
            },
        ),
    ]
